# Generated by Django 2.0.6 on 2018-06-27 02:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Palestra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=200)),
                ('palestrante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('feita_em', models.DateTimeField(auto_now_add=True)),
                ('aceita_em', models.DateTimeField(null=True)),
                ('palestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='palestras.Palestra')),
            ],
        ),
    ]
