# Generated by Django 2.0.6 on 2018-06-27 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('palestras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palestra',
            name='descricao',
            field=models.CharField(max_length=200, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='palestra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='palestras.Palestra'),
        ),
    ]
